[package]
name = "process_supervisor"
version = "0.1.0"
authors = ["Hector Ortega <hector.oj@gmail.com>"]

[dependencies]
rocket = "0.3.0"
rocket_codegen = "0.3.0"
rocket_contrib = "0.3.0"
serde_derive = "1.0.10"
serde_json = "1.0.2"
serde = "1.0.10"
